---
name: cicd pipeline
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

# set  top-level permissions
# Default permissions for all jobs
permissions:
  contents: read
  packages: read

jobs:
  job-1-run-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch entire history
          fetch-depth: 0
      # Step: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "14.x"
          # Cache npm dependencies for faster builds
          cache: "npm"
      - name: Install dependencies
        run: npm install

# ---------------------------

  job-2-run-security-check:
    needs: ['job-1-run-checkout']
    name: gitleaks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

# ---------------------------

  job-3-run-code-lint:
    needs: ["job-2-run-security-check"]
    runs-on: ubuntu-latest
    # Explicitly set permissions for this job
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Super-linter
        uses: super-linter/super-linter@v6.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

  run-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate changelog
        run: |
          git log --pretty=format:"* %h - %an, %ar : %s" \
            > CHANGELOG.md
          cat CHANGELOG.md
