# Define the name of the CI/CD pipeline
name: cicd pipeline

# events that trigger this pipeline
on:
  pull_request:
    branches:
      # all branches
      - '*'  

  push:
    branches:
      - main 

# job 1 ------------------------------

jobs:
  run-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch entire history
          fetch-depth: 0

        # install node.js
      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14.x'
          # Cache npm dependencies for faster builds
          cache: 'npm'  

      - name: install dependencies
        # Install npm dependencies for the project
        run: npm install  

  # job 2 ------------------------------

  # run security checks
  security-check-stage:
    needs: ['run-checkout']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # fetch complete commit history for accurate scanning
          fetch-depth: 0
          path: './'
      
        # install trufflehog packages
      - name: pip install install trufflehog
        run: |
          python -m pip install --upgrade pip
          pip install truffleHog

      - name: trufflehog scan
        uses: trufflesecurity/TruffleHog-Enterprise-Github-Action@main
        with:    
          args: "--debug ${{ github.repository }} main HEAD"
          
  # job 3 ------------------------------

  # Job to generate changelog based on commit history
  run-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch complete commit history for accurate scanning
          fetch-depth: 0

      - name: Generate changelog
        run: |
          git log --pretty=format:"* %h - %an, %ar : %s" > CHANGELOG.md
          cat CHANGELOG.md