---
name: cicd pipeline

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

jobs:
  job-1-run-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch entire history
          fetch-depth: 0 
      # Step: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "14.x"
          # Cache npm dependencies for faster builds
          cache: "npm"
      - name: Install dependencies
        run: npm install

  # Job 2
  job-2-run-security-check:
    needs: ["job-1-run-checkout"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: "./"
      - name: Install TruffleHog
        run: |
          python -m pip install --upgrade pip
          pip install truffleHog
      - name: TruffleHog scan
        uses: trufflesecurity/TruffleHog-Enterprise-Github-Action@main
        with:
          args: --fail-verified --debug ${{ github.event.repository.default_branch }} HEAD

  # Job 3:
  job-3-run-code-lint:
    needs: ["job-2-run-security-check"]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
      statuses: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Super-linter
        uses: super-linter/super-linter@v6.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

  # Job 3:
  run-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate changelog
        run: |
          git log --pretty=format:"* %h - %an, %ar : %s" \
            > CHANGELOG.md
          cat CHANGELOG.md
