name: cicd pipeline
on:
  pull_request:
    # trigger when pull_requests are made to all branches
    branches:
      - '*'

  push:
    branches:
      # trigger on pushes to the main branch
      - main

jobs:
  run-checkout:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          # fetch minimal history
          fetch-depth: 1
          # check path
          path: ./DevOps-Forge

      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14.x'
          cache: 'npm'

      - name: install dependencies
        run: npm install
        working-directory: ./DevOps-Forge

      - name: run tests
        run: npm test
        working-directory: ./DevOps-Forge

  run-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: checkout checkout repository
        uses: actions/checkout@v4
        with:
          # fetch full history for changelog
          fetch-depth: 0
          path: ./DevOps-Forge
        
      - name: generate changelog
        run: |
          git log --pretty=format:"%h - %an, %ar : %s"
        working-directory: ./DevOps-Forge
