---
name: cicd pipeline
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main

# set  top-level permissions
# Default permissions for all jobs
permissions:
  contents: read
  packages: read

# ---------------------------

# workflow jobs
jobs:
  job-1-run-checkout:
    name: "job 1: run checkout"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch entire history
          fetch-depth: 0
      # Step: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "14.x"
          # Cache npm dependencies for faster builds
          cache: "npm"
      - name: Install dependencies
        run: npm install

# ---------------------------

  # gitleaks security scan
  job-2-run-security-check:
    name: "job 2: security scan"
    needs: ['job-1-run-checkout']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          # environment variables
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
          GITLEAKS_VERSION: "lastest"
          GITLEAKS_ENABLE_SUMMARY: "true"

# ---------------------------

  # run lint for checks
  job-3-run-code-lint:
    name: "Job 3: run code lint"
    needs: ["job-2-run-security-check"]
    runs-on: ubuntu-latest
    # Explicitly set permissions for this job
    permissions:
      contents: read
      packages: read
      statuses: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Super-linter
        uses: super-linter/super-linter@v6.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}

# ---------------------------

  # run dependency review
  job-4-run-dependency-review:
    name: "job-4: run dependency check"
    needs: ['job-3-run-code-lint']
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency checks'
        uses: actions/dependency-review-action@v4
        with:
          fail-on-severity: high
          vulnerability-check: true

# ---------------------------

  # run outdated dependency checker
  job-5-check-outdated-dependencies:
    name: "job 5: check outdated dependencies"
    needs: ['job-4-run-dependency-review']
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
      - name: run outdate check
        uses: odanado/outdated-check-action@v0
        id: outdate-check

# --------------------------- 

  run-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate changelog
        run: |
          git log --pretty=format:"* %h - %an, %ar : %s" \
            > CHANGELOG.md
          cat CHANGELOG.md
