# Define the name of the CI/CD pipeline
name: cicd pipeline

# Specify the events that trigger this pipeline
on:
  pull_request:
    # Trigger when pull requests are made to all branches
    branches:
      # all branches
      - '*'  

  push:
    branches:
      # Trigger on pushes to the main branch
      - main 

jobs:
  run-checkout:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch entire history
          fetch-depth: 0

        # install node.js
      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: '14.x'
          # Cache npm dependencies for faster builds
          cache: 'npm'  

      - name: install dependencies
        # Install npm dependencies for the project
        run: npm install  

  # job 2 ---------------

  # run security checks
  security-check-stage:
    needs: ['run-checkout']
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          path: './'
      
        # install trufflehog packages
      - name: pip npm install trufflehog
        run: |
          pip install truffleHog
          echo "successfull installed packages"
          
      - name: run trufflehog
        run: |
          trufflehog git file://. --since-commit main --branch feature-1 --only-verified --fail

  # job 3 ---------------

  # Job to generate changelog based on commit history
  run-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          # Fetch full commit history to generate accurate changelog
          fetch-depth: 0

      - name: Generate changelog
        run: |
          git log --pretty=format:"* %h - %an, %ar : %s" > CHANGELOG.md
          cat CHANGELOG.md