---
name: CICD Pipeline
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - main
jobs:
  job-1:
    name: "job 1: run checkout"
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: "14.x"
          cache: "npm"
      - name: install dependencies
        run: npm install

  job-2:
    needs: ["job-1"]
    name: "job-2-run-security-check"
    runs-on: ubuntu-latest
    steps:
      - name: 324
        uses: ./.github/workflows/job-2.yml
